let words = {
    "немає": "there is not",
    "жовті": "Yellow",
    "кожен": "each",
    "переглядати": "revise",
    "и": "and",
    "дізнатися": "find out",
    "свої": "your",
    "там": "there",
    "забули": "forgot",
    "вивчення": "study",
    "приклади": "examples",
    "слова": "words",
    "нотатки": "notes",
    "з": "with, from",
    "ставити": "put",
    "запас": "stock",
    "фрази": "phrases",
    "поставите": "place",
    "створений": "generated",
    "перейти": "go over, walk over",
    "котрий": "which",
    "стати": "to become",
    "нам": "us",
    "допомагають": "help",
    "сердця": "The heart",
    "щирого": "pure",
    "сказані": "said",
    "неважливо": "Does not matter",
    "таки": "still",
    "сказати": "to say",
    "отже": "Therefore",
    "яка": "which or what is the",
    "людину": "man",
    "називають": "call",
    "красномовною": "Eloquent",
    "справді": "Indeed",
    "й": "and",
    "чудовий": "Excellent",
    "красний": "good, excellent",
    "речі": "things",
    "красно": "red",
    "словами": "words",
    "підсилити": "strengthen",
    "вдячності": "Gratitude",
    "висловлювання": "statement",
    "формою": "shape",
    "етикетною": "Etiquette",
    "поширеною": "common",
    "зрослася": "Grew up",
    "часом": "sometimes",
    "сполука": "Compound",
    "ця": "This",
    "спаси": "Save it",
    "сполуки": "Compound",
    "від": "from",
    "походить": "comes",
    "воно": "It",
    "століття": "century",
    "го": "NGO",
    "шістнадцятого": "Sixteenth",
    "із": "from / with",
    "пам'ятках": "Monuments",
    "писемних": "Written",
    "наших": "our",
    "живе": "lives",
    "яке": "what",
    "словом": "in short",
    "висловлювати": "to express",
    "можна": "it is possible",
    "вдячність": "appreciation, gratitude",
    "спасибі": "Thanks",
    "мові": "language",
    "українській": "Ukrainian",
    "сільпо": "Silpo",
    "магазин": "shop",
    "гуртожиток": "hostel",
    "йду": "going",
    "йдеш": "You go",
    "зараз": "right now",
    "каву": "coffee",
    "чай": "tea",
    "сік": "juice",
    "воду": "water",
    "пити": "drink",
    "піцу": "pizza",
    "рибу": "fish",
    "торт": "cake",
    "сир": "cheese",
    "рис": "rice",
    "м'ясо": "meat",
    "їсти": "eat",
    "гуляти": "walk",
    "українські": "Ukrainian",
    "музику": "music",
    "співати": "sing",
    "танцювати": "dance",
    "телевізор": "TV",
    "дивитися": "watch",
    "книги": "Books",
    "любиш": "love",
    "сестри": "sisters",
    "нема": "there is not",
    "ні": "No",
    "так": "Yes",
    "сестра": "sister",
    "чи": "or",
    "гуртожитку": "hostel, dormitory",
    "живу": "(I) live",
    "університеті": "University",
    "педагогічному": "Pedagogical",
    "вчуся": "I study",
    "вчишся": "Learn",
    "я": "I",
    "ти": "you",
    "звідки": "from where",
    "дев'ятнадцять": "nineteen",
    "вісімнадцять": "eighteen",
    "років": "years",
    "скільки": "How many",
    "дякую": "thank you",
    "мені": "me",
    "теж": "too, also",
    "тобі": "you",
    "свій": "his",
    "помилках": "mistakes",
    "основі": "on",
    "звіту": "report",
    "зі": "with",
    "зберігати": "save",
    "помилки": "Errors",
    "вказані": "These",
    "звіті": "report",
    "отримаєте": "get",
    "звіт": "report",
    "виправить": "to fix",
    "роботу": "work",
    "вашу": "your",
    "репетитор": "tutor",
    "записи": "records",
    "ваші": "your",
    "виправити": "correct",
    "пишіть": "write",
    "репетитора": "tutor",
    "попросити": "ask",
    "думати": "think",
    "допомагає": "helps",
    "навіть": "even, yet",
    "себе": "myself, yourself, himself, herself, itself ...",
    "писати": "to write",
    "письмо": "writing",
    "готові": "ready to",
    "олександр": "Alexander",
    "мене": "me",
    "тебе": "you",
    "привіт": "Hello",
    "приємно": "Nicely",
    "граматичні": "grammatical",
    "якщо": "if",
    "та": "and, that",
    "міткою": "tag",
    "такою": "such",
    "мітку": "label",
    "використовуються": "used",
    "допоможе": "help",
    "створеного": "created",
    "створюєте": "create",
    "кожного": "each",
    "робити": "do",
    "викладачеві": "teacher",
    "поставити": "put",
    "запитання": "QUESTION",
    "є": "is",
    "флешкарти": "flash cards",
    "використовувати": "use",
    "переглянути": "review",
    "словника": "dictionary",
    "сторінку": "page",
    "запам'ятати": "remember",
    "регулярно": "regularly",
    "словниковий": "lexical",
    "необхідно": "necessary",
    "вчитеся": "learn",
    "що": "what / that",
    "означає": "means",
    "продовжуйте створювати": "keep creating",
    "продовжуйте": "Continue",
    "деякі з цих": "some of these",
    "ви побачите багато": "you will see a lot",
    "це хороша ідея": "This is a good idea",
    "бачитимете": "you will see",
    "уроці": "lesson",
    "кожному": "each",
    "у": "in",
    "ідея": "idea",
    "хороша": "Good",
    "створювати": "create",
    "також": "Also",
    "жовтим": "yellow",
    "стало": "become",
    "тепер": "now",
    "колір": "color",
    "синє": "blue",
    "потім": "then",
    "змінює": "change",
    "створення": "Creation",
    "ів": "Yves",
    "створенням": "creation",
    "називається": "called",
    "незнайомі": "unfamiliar",
    "зберігатимете": "will save",
    "синіх": "blue",
    "нові": "New",
    "знаєте": "know",
    "деякі": "Some",
    "побачите": "You'll see",
    "можете": "can",
    "трохи": "slightly",
    "потрібно": "required",
    "має": "has",
    "скоро": "soon, shortly",
    "пішки": "on foot, walk",
    "все": "all, everything",
    "вранці": "in the morning",
    "їдете": "Coming",
    "увечері": "In the evening",
    "йдете": "go",
    "коли": "When",
    "читання": "reading",
    "слухати": "to listen",
    "слухання": "hearing",
    "читати": "to read",
    "дуже": "very",
    "навчайтеся": "learn",
    "цікаві": "interesting",
    "уроки": "lessons",
    "брата": "brother",
    "де": "Where",
    "говорить": "says, speaks",
    "гарний": "good",
    "завтра": "tomorrow",
    "куди": "Where",
    "легким": "easy",
    "люблю": "love, like",
    "живеш": "you live",
    "обирайте": "Choose",
    "легшими": "easier",
    "виберете": "Choose",
    "вітаємо": "welcome",
    "гарно": "good",
    "жовтих": "yellow",
    "великобританії": "Great Britain",
    "навчитеся": "learn",
    "німеччини": "Germany",
    "говорити": "to speak / talk",
    "всі": "all",
    "одне": "one",
    "важливо": ";Importantly",
    "а": "and",
    "або": "or",
    "більше": "greater",
    "mp": "mp",
    "бувай": "Bye",
    "вами": "you",
    "будуть": "will",
    "артур": "Arthur",
    "будете": "will",
    "багато": "Many, much, lots",
    "більш": "More",
    "вас": "you",
    "брат": "brother",
    "буде": "it will, will be",
    "боже": "God",
    "ближчими": "Closer",
    "lingq": "LingQ",
    "автобусі": "buses",
    "в": "in, to, of, from, at, on, by",
    "вам": "you",
    "слово": "word",
    "і": "And",
    "краще": "better",
    "цих": "these",
    "ж": "same",
    "іншої": "other",
    "людини": "people, man",
    "однієї": "One",
    "світла": "light",
    "добра": "good",
    "енергію": "power",
    "передають": "convey",
    "вони": "they",
    "розуміння": "understanding",
    "зрозуміти": "understand",
    "намагатиметеся": "try to",
    "матеріалами": "materials",
    "виберіть": "Select",
    "складні": "complex",
    "цікаво": "Interesting",
    "за": "By",
    "ви": "you",
    "на": "on",
    "для": "for",
    "дня": "day",
    "оберіть": "select",
    "розуміти": "understand",
    "одного": "One",
    "не": "Not",
    "заговорите": "conspiracy",
    "як": "As",
    "ласкаво": "welcome",
    "хочете": "want",
    "це": "it. this, that",
    "добре": "Good",
    "нових": "new",
    "мову": "language",
    "звати": "call",
    "нову": "new",
    "до": "to or until",
    "просимо": "Please",
    "мовою": "language",
    "новою": "new",
    "ласкаво просимо": "welcome",
    "справи": "affair",
    "перший": "first",
    "слів": "words",
    "щоб": "that",
    "вивчити": "explore",
    "насолоджуватися": "enjoy",
    "вчити": "teach",
    "того": "of that",
    "спосіб": "way",
    "найкращий": "best",
    "стануть": "will become",
    "незабаром": "soon, before long",
    "цікавими": "interesting",
    "важким": "difficult",
    "вчитися": "Learn",
    "складним": "complicated",
    "надто": "too",
    "котрі": "Which",
    "фраз": "phrases",
    "урок": "lesson",
    "значення": "importance, significance",
    "дізнайтеся": "learn",
    "їх": "their and them",
    "ласка": "affection, kindness",
    "зрозумієте": "understand",
    "забудете": "Forget about",
    "будь": "ANY",
    "прочитайте": "Read it",
    "розумітимете": "you will understand",
    "спершу": "at first",
    "цікавим": "interesting",
    "небагато": "not a lot",
    "лише": "only 10% ten percent",
    "цією": "This",
    "прослухайте": "listen",
    "який": "which",
    "плеєрі": "players",
    "разів": "times",
    "послухайте": "hear",
    "крок": "step",
    "правила": "rules",
    "спочатку": "first",
    "дізнаєтесь": "learn",
    "навчатись": "to study",
    "лісом": "wood",
    "дід": "grandfather",
    
}